### ISSUE TITLE
The breadcrumb in listing page show undefined variable 'cat_ids'

### ISSUE THREAD

**Issue by smallcar88** [luxifyit/luxify-staging#2]
`ErrorException in Front.php line 377:
Undefined variable: cat_ids`

**Comment by smallcar88** [comment]
Arung, I think this is the problem of the mapping with new categories structure 
Like this one: [http://staging.luxify.com/listing/cannes-californie-luxury-apartment](url)

The category 'property' doesn't exist in the new main category, and thats why it return such error ?

**Comment by MibuSawatori** [comment]
I know that, I'm making algorithm for the fixes.
